### ISSUE TITLE
Dev dig-etl-engine cannot load atf doc

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/dig-etl-engine#147]

**Comment by szeke** [comment]
The current version of dig-etl-engine that we get from dev will throw an error in ES when loading the attached doc. To reproduce, create an empty dgi-etl project, add the single doc and run, there will be no docs in ES, and an error:
```
elasticsearch_1    | MapperParsingException[failed to parse]; nested: IllegalArgumentException[mapper [knowledge_graph.website.provenance.confidence.extraction] of different type, current_type [long], merged_type [double]];
elasticsearch_1    | 	at org.elasticsearch.index.mapper.DocumentParser.parseDocument(DocumentParser.java:156)
elasticsearch_1    | 	at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:309)
elasticsearch_1    | 	at org.elasticsearch.index.shard.IndexShard.prepareIndex(IndexShard.java:584)
elasticsearch_1    | 	at org.elasticsearch.index.shard.IndexShard.prepareIndexOnPrimary(IndexShard.java:563)
elasticsearch_1    | 	at org.elasticsearch.action.index.TransportIndexAction.prepareIndexOperationOnPrimary(TransportIndexAction.java:211)
elasticsearch_1    | 	at org.elasticsearch.action.index.TransportIndexAction.executeIndexRequestOnPrimary(TransportIndexAction.java:223)
elasticsearch_1    | 	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardIndexOperation(TransportShardBulkAction.java:327)
elasticsearch_1    | 	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:120)
elasticsearch_1    | 	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:68)
elasticsearch_1    | 	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryPhase.doRun(TransportReplicationAction.java:657)
elasticsearch_1    | 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
elasticsearch_1    | 	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:287)
elasticsearch_1    | 	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:279)
elasticsearch_1    | 	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:77)
elasticsearch_1    | 	at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:378)
elasticsearch_1    | 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
elasticsearch_1    | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
elasticsearch_1    | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
elasticsearch_1    | 	at java.lang.Thread.run(Thread.java:748)

```

**Comment by szeke** [comment]
Input file to reproduce the error
[armslist_test.jl.gz](https://github.com/usc-isi-i2/dig-etl-engine/files/1570392/armslist_test.jl.gz)

**Comment by jasonslepicka** [comment]
@saggu i think your new release should fix this.  can you update dev on dig-etl-engine and test it?
 https://github.com/usc-isi-i2/dig-sandpaper/releases/tag/0.1.4-r058

**Comment by saggu** [comment]
@jasonslepicka the mapping is overwritten by https://github.com/usc-isi-i2/dig-sandpaper/blob/master/digsandpaper/elasticsearch_mapping/generate.py#L89
It is on my todo list. I am on vacation starting yesterday.

**Comment by jasonslepicka** [comment]
@saggu i pushed a fix for that line.  can you verify it on this release?

https://github.com/usc-isi-i2/dig-sandpaper/releases/tag/0.1.4-r059
