### ISSUE TITLE
Time Series extractions throws exception

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/dig-etl-engine#205]
While processing https://github.com/usc-isi-i2/elicit_alignment/tree/master/m5/datasets/api_cmr_ds2_v2

```
Traceback (most recent call last):
  File "extract_and_import.py", line 112, in parse_raw_files
    ts_converted_output_file_path = self.run_ts(file_name, file_path)
  File "extract_and_import.py", line 214, in run_ts
    timeseries = es.process()
  File "../../../dig/dig-etl-engine/utilities/timeseries/extractSpreadsheet.py", line 280, in process
    for parsed_tsr in tsr.parse(data):
  File "../../../dig/dig-etl-engine/utilities/timeseries/extractSpreadsheet.py", line 35, in parse
    self.parse_ts(data, metadata)
  File "../../../dig/dig-etl-engine/utilities/timeseries/extractSpreadsheet.py", line 123, in parse_ts
    raise ie
IndexError: Index out of range

**Comment by szeke** [comment]
@GreatYYX can you run the extract script on this dataset?

**Comment by szeke** [comment]
I tested `api_ben_ds2_v2` and it works, somehow `_cmr_` is different
